### ISSUE TITLE
Frightening effects when going on EVA

### ISSUE THREAD

**Issue by zeroinformatique** [SerTheGreat/G-Effects#7]
As soon as I go EVA the screen turns red (probably because of the lag).
This is very frightening :)

**Comment by SerTheGreat** [comment]
This is most likely because of the game's physics bug causing a kerbal to have extreme Gs at the moment of going EVA. It has been an annoying issue in pre-0.2.1 versions but it was fixed then, so make sure you are using the latest (0.2.2) version of the mod. If the version is the latest, find the gDampingThreshold parameter in G-Effects.cfg file and try to lower it to a reasonable value but don't set it too low for not having natural G values damped.

**Comment by zeroinformatique** [comment]
Seems to work to far with 0.5. 
Might be interesting to push that value to the default release if it works as intended.

**Comment by SerTheGreat** [comment]
Do you mean that you've set the parameter to be equal to 0.5? If so then it's too low because that means the damping algorithm starts to restrict the mod when acceleration immediately rises to just 1/2 G and proceeds until acceleration drops below that value. Don't know exactly whether that's normally possible in KSP physics but suppose that is. So your setting may lead to the mod not applying any effects when it should.
Please, provide the following information:
The situation when you have the issue: in orbit or landed?
The name of the crew pod you use
Or your savegame file (if it is with not much than stock + G-Effects)
output_log.txt from KSP_Data subfolder (put it on some file sharing service)

**Comment by zeroinformatique** [comment]
Sorry, I meant I reduced it by 50% (0.5) :
gDampingThreshold = 50

The effect occurs most of the time immediately after going EVA from Command pod Mk1. There's a tiny lag when the game computes the EVA, and that lag seems to create a massive G-Effect boost.

It happens in both space or landed. But the biggest effect I had was in space around Kerbin.

A possible fix would be to temporary ignore Gs a second after going EVA.

**Comment by SerTheGreat** [comment]
Since there's a workaround for the issue I prefer to wait for KSP 1.1 as it would require an imminent update anyway and then implement some extended logic for this together with some minor improvements.

**Comment by SerTheGreat** [comment]
Damping threshold lowered to 44 G by default in version 0.2.3. That solves the issue.
